---
# tasks file for ansible-chrony
- name: Fail if not rhel7
  fail:
    msg: "You must run this playbook in rhel7 servers"
  when: ansible_distribution_major_version != "7"
- name: Config chrony 
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - restart chrony
