---
- name: Fail to run if not rhel6
  fail:
    msg: "This must be run on rhel6 systems"
  when: ansible_distribution_major_version != "6"
  
- name: Install Packages 
  yum: 
    name: ntp 
    state: latest

- name: Configure  timezone
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes
  when: ntp_timezone is defined

- name: Configure  ntp.conf
  template: 
    src: ntp.conf.j2 
    dest: /etc/ntp.conf 
    mode: 0644 
    owner: root 
    group: root
  notify: 
  - restart ntp
