---
- name: creating new LVM volume group
  lvg: vg={{ create_vgname }} pvs={{ new_disk }} state=present
  when: create and config_lvm
  tags: 
  - create_lv

- name: creating new LVM logical volume
  lvol: vg={{ create_vgname }} lv={{ create_lvname }} size={{ create_lvsize }}
  when: create and config_lvm
  tags: 
  - create_lv

- name: creating new filesystem on new LVM logical volume
  filesystem: fstype={{ filesystem }} dev=/dev/{{ create_vgname }}/{{ create_lvname }}
  when: create and config_lvm
  tags: 
  - create_lv

- name: mounting new filesystem
  mount: name={{ new_mntp }} src=/dev/{{ create_vgname }}/{{ create_lvname }} fstype={{ filesystem }} state=mounted opts=defaults,acl
  when: create and config_lvm
  tags: 
  - create_lv
  - mount

- name: extending existing LVM volume group
  lvg: vg={{ extend_vgname }} pvs={{ extend_disks }}
  when: extend and config_lvm
  tags: extend_vg

- name: extending existing filesystem
  command: lvextend {{ lvextend_options }} /dev/{{ extend_vgname }}/{{ extend_lvname }}
  when: extend and config_lvm
  tags: extend_lv

- name: resizing filesystem
  filesystem: dev=/dev/{{ resize_vgname }}/{{ resize_lvname }} resizefs= yes fstype={{ filesystem }}
#  command: resize2fs /dev/{{ resize_vgname }}/{{ resize_lvname }}
  when: resize and config_lvm
  tags: extend_lv
